In [ ]:
import pandas as pd
import pyodbc 

server = 'DESKTOP-33OODCP' 
database = 'Python' 
conexaoDB = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                      f'SERVER={server};'
                      f'DATABASE={database};'
                      'Trusted_Connection=yes;')

cursor = conexaoDB.cursor()   # criando cursor de comando

In [ ]:
Query = """
select * from [dbo].[Items]
where total_price > 5000

"""

In [ ]:
Vendas = pd.read_sql(Query,conexaoDB)
Vendas.head(10)

Criar Conexão com 2° banco de dados

In [ ]:
server2 = 'DESKTOP-33OODCP' 
database2 = 'Produtos' 
conexaoDB2 = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                      f'SERVER={server2};'
                      f'DATABASE={database2};'
                      'Trusted_Connection=yes;')

cursor2 = conexaoDB2.cursor()   # criando cursor de comando

In [ ]:
Query2="""

SELECT *
FROM [Produtos].[dbo].[Dim_Produto]

"""

In [ ]:
Produtos= pd.read_sql(Query2,conexaoDB2)

In [ ]:
Vendas.head(5)

    id  order_id  product_id  quantity  total_price
0   29      5849          14         4       7096.0
1  133      1067          24         4      10652.0
2  160      1497          24         5      13315.0
3  168       614          10         4       7808.0
4  217      2736          23         2       5590.0

In [ ]:
Produtos.head(5)

  Id                  Name   Price Id_Category
0  0       Sapato vermelho    96.0           0
1  1  Bolsa mais que Velha  8000.0           0
2  2                 Calça    75.0           0
3  3    Camisa apertadinha   170.0           0
4  4   Vestido Super curto    57.0           0

In [ ]:
Vendas ["product_id"] = Vendas ["product_id"].astype(int)
Produtos ["Id"] = Produtos ["Id"].astype(int)

In [ ]:
join = pd.merge(Vendas,Produtos,left_on="product_id",right_on="Id",how="left")

In [ ]:
join.head(10)

,id,order_id,product_id,quantity,total_price,Id,Name,Price,Id_Category
0,29,5849,14,4,7096.0,14,Máquina de Secar,1774.0,2
1,29,5849,14,4,7096.0,14,Máquina de Secar,1774.0,2
2,133,1067,24,4,10652.0,24,Nóquia,2663.0,4
3,133,1067,24,4,10652.0,24,Nóquia,2663.0,4
4,160,1497,24,5,13315.0,24,Nóquia,2663.0,4
5,160,1497,24,5,13315.0,24,Nóquia,2663.0,4
6,168,614,10,4,7808.0,10,Geladeira,1952.0,2
7,168,614,10,4,7808.0,10,Geladeira,1952.0,2
8,217,2736,23,2,5590.0,23,Ruaei,2795.0,4
9,217,2736,23,2,5590.0,23,Ruaei,2795.0,4

In [ ]:
cursor.close
conexaoDB.close
cursor2.close
conexaoDB2.close