In [1]:
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account
from pandas_gbq import to_gbq
from datetime import datetime

In [2]:
df = pd.read_excel(r'C:\curso-eng-dados\Python-SGBDS\Origem de Dados\arquivos_excel\Ordens.xlsx')
df.head()

   id          created_at  customer_id              status
0   0 2019-08-28 03:36:31           91            entregue
1   1 2019-08-16 20:21:30            7            entregue
2   2 2019-07-11 11:00:06           26  pagamento_pendente
3   3 2019-08-27 21:04:41           92  pagamento_pendente
4   4 2019-11-03 19:58:37           63    entrega_pendente

In [3]:
tipos_de_dados = df.dtypes
print(tipos_de_dados)

id                      int64
created_at     datetime64[ns]
customer_id             int64
status                 object
dtype: object

In [ ]:
# filto no meu dataflame antes de realizar a carga (apenas o mês e ano atuais)
"""
hoje = datetime.now()
mes_atual = hoje.month
ano_atual = hoje.year

df_filtrado = df[(df['created_at'].dt.month == mes_atual) & (df['created_at'].dt.year == ano_atual)]


"""

In [ ]:
#hoje = datetime.now().year
#print(hoje)

In [ ]:
#df_filtrado.head(5)

In [4]:
hoje = datetime.now()
mes_atual = hoje.month
ano_atual = hoje.year

df = df[(df['created_at'].dt.month == mes_atual) & (df['created_at'].dt.year == ano_atual)]

In [5]:
df.head()

        id          created_at  customer_id            status
1400  1400 2025-06-21 16:00:00           49  entrega_pendente
1793  1793 2025-06-21 16:00:00           29          entregue
1804  1804 2025-06-21 16:00:00            6          entregue
2527  2527 2025-06-21 16:00:00           10          carrinho
2554  2554 2025-06-21 16:00:00           31          carrinho

In [6]:


# Especifique o caminho para o arquivo JSON de credenciais
credencial = r'C:\curso-eng-dados\Python-SGBDS\Origem de Dados\pythoncurso-462414-f5463d5035ab.json'

# Crie um cliente BigQuery usando as credenciais
clientacao = bigquery.Client.from_service_account_json(credencial)

In [7]:
comandoapagar = """ 

 delete
 FROM `pythoncurso-398511.AulaPython.Ordens`
 where FORMAT_TIMESTAMP('%Y', created_at)  = FORMAT_TIMESTAMP('%Y', CURRENT_DATE())
 and  FORMAT_TIMESTAMP('%m', created_at)  = FORMAT_TIMESTAMP('%m', CURRENT_DATE())


"""
# Execute a consulta
apagardados = clientacao.query(comandoapagar)

https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements

In [10]:

# credenciais para validar importar dados para o google bigquery
CredImportacao = service_account.Credentials.from_service_account_file(
    credencial,
    scopes=['https://www.googleapis.com/auth/bigquery']
)

#variaveis do projeto 
projeto = 'pythoncurso-462414'
dataset = 'AulaPython'
tabela = 'Ordens'
parameretro ='append'      
#replace = subistuir a antiga pela original 
#append = adiciona dados no fim da tabela

In [11]:
df.to_gbq(destination_table=f'{projeto}.{dataset}.{tabela}',   
          project_id=projeto,
          if_exists=parameretro,
          credentials=CredImportacao)

C:\Users\guspe\AppData\Local\Temp\ipykernel_13424\3854577455.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  df.to_gbq(destination_table=f'{projeto}.{dataset}.{tabela}',

In [12]:
"""  

SELECT *
,extract(YEAR  FROM created_at) as ano
,extract(month  FROM created_at) as mes
,FORMAT_TIMESTAMP('%Y', created_at) AS anoFormat
,FORMAT_TIMESTAMP('%m', created_at) AS mesformat
,CURRENT_DATE() hoje
 FROM `pythoncurso-398511.AulaPython.Ordens` 


"""

"  \n\nSELECT *\n,extract(YEAR  FROM created_at) as ano\n,extract(month  FROM created_at) as mes\n,FORMAT_TIMESTAMP('%Y', created_at) AS anoFormat\n,FORMAT_TIMESTAMP('%m', created_at) AS mesformat\n,CURRENT_DATE() hoje\n FROM `pythoncurso-398511.AulaPython.Ordens` \n\n\n"

In [13]:
#Delete
"""

delete FROM `pythoncurso-398511.AulaPython.Ordens` 
 where FORMAT_TIMESTAMP('%Y', created_at) = FORMAT_TIMESTAMP('%Y', CURRENT_DATE())
 and  FORMAT_TIMESTAMP('%m', created_at) = FORMAT_TIMESTAMP('%m', CURRENT_DATE())
"""

"\n\ndelete FROM `pythoncurso-398511.AulaPython.Ordens` \n where FORMAT_TIMESTAMP('%Y', created_at) = FORMAT_TIMESTAMP('%Y', CURRENT_DATE())\n and  FORMAT_TIMESTAMP('%m', created_at) = FORMAT_TIMESTAMP('%m', CURRENT_DATE())\n"